version: "3"
services:
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "conf:/etc/nginx/conf.d"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:ro"
    nginx-gen:
        restart: always
        image: jwilder/docker-gen
        container_name: nginx-gen
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "/root/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
            - "conf:/etc/nginx/conf.d"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:ro"
        entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    letsencrypt-nginx-proxy-companion:
        restart: always
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-nginx-proxy-companion
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "conf:/etc/nginx/conf.d"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:rw"
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
            - NGINX_PROXY_CONTAINER=nginx
    registry:
        restart: always
        build:
            context: /root/service
            dockerfile: /root/service/docker/Dockerfile
        image: polyswarm/worker-registry
        container_name: registry
        expose:
            - "8000"
        command: ["worker-registry",
            "--eth-uri",
            "${ETH_URI}",
            "--ipfs-uri",
            "https://ipfs.infura.io:5001/",
            "--registry-address",
            "${REGISTRY_ADDRESS}"
        ]
        environment:
            - VIRTUAL_HOST=gamma-registry.polyswarm.network
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=gamma-registry.polyswarm.network
            - LETSENCRYPT_EMAIL=info@polyswarm.io
volumes:
    certs:
    conf:
    vhost:
    html:
