image: docker:stable

stages:
    - test
    - build

services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

py35:
    image: python:3.5
    stage: test
    script: tox -e py35
    
variables:
    DOCKER_HUB_REGISTRY: "https://index.docker.io/v1/"

build-master:
    stage: build
    only: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"
    stage: build
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
        - docker push $DOCKER_FULL_PATH

build-non-master:
    stage: build
    except: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    stage: build
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
        - docker push $DOCKER_FULL_PATH
