stages:
    - test
    - build

test-python35:
    image: python:3.5
    stage: test
    before_script:
        - pip install tox
    script: tox -e py35
    
build-master:
    image: docker:stable
    only: 
        - master
    tags:
        - docker
    variables:
        DOCKER_HUB_REGISTRY: "https://index.docker.io/v1/"
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"
    stage: build
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
        - docker push $DOCKER_FULL_PATH

build-non-master:
    image: docker:stable
    except: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    stage: build
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
        - docker push $DOCKER_FULL_PATH
