stages:
    - testpy
    - testjs
    - build

test-python35:
    image: python:3.5
    stage: testpy
    tags:
        - docker
    before_script:
        - pip install tox
    script: tox -e py35

test-node:
    image: node
    stage: testjs
    tags:
        - docker
    script:
        - cd cli
        - yarn install
        - yarn test

build-master:
    image: docker:stable
    only:
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"
    stage: build
    services:
        - docker:dind
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .

build-non-master:
    image: docker:stable
    except:
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    stage: build
    services:
        - docker:dind
    script:
        - docker build -t $DOCKER_FULL_PATH -f docker/Dockerfile .
